/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./../components/layout/AppBreadcrumb.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppMain: typeof import('./../components/layout/AppMain.vue')['default']
    AppSidebar: typeof import('./../components/layout/AppSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    PageContainer: typeof import('./../components/common/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/common/SearchForm.vue')['default']
    SidebarItem: typeof import('./../components/layout/SidebarItem.vue')['default']
    TableActions: typeof import('./../components/common/TableActions.vue')['default']
  }
}
